services:
  - type: web
    name: fastmcp-server
    runtime: python
    buildCommand: bash render-build.sh
    startCommand: python src/server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
